### ISSUE TITLE
Question: What's the total runtime memory footprint of a single node of Akka cluster on Graal native?

### ISSUE THREAD

**Issue by shafqatevo** [vmencik/akka-graal-config#13]
Hi @vmencik, thanks for this work!

Just had this quick question: what's the total runtime memory footprint of a single node of Akka cluster on Graal native at boot up?

**Comment by vmencik** [comment]
I don't have exact numbers but looking at my notes from when I converted one of our services built with akka-http to GraalVM native the memory footprint was about 20-30% when compared to running the same service in standard JVM. This was real-world service that had exposed REST API implemented with akka-http.
Also this was about a year ago and your results may vary depending on what your application actually does. But the memory footprint reduction was significant. You can try building and running https://github.com/vmencik/akka-graal-native and measuring the footprint yourself. That is just a very simple akka-http service with no other dependencies.

**Comment by shafqatevo** [comment]
Thanks @vmencik we'll try asap.
