### ISSUE TITLE
How to import AkkaSubstitutions

### ISSUE THREAD

**Issue by raboof** [vmencik/akka-graal-config#4]
It looks like just depending on `graal-akka-actor` is not sufficient to pull in the `AkkaSubstitutions`. Let's see if we can make that automatic, or document how to do it. Or perhaps we can refactor something upstream to make it no longer necessary?

**Comment by vmencik** [comment]
It works for me. I didn't publish these yet so I only tested with `publishLocal` but I was able to remove the substitution in the example repo and just depend on `graal-akka-actor`.

**Comment by vmencik** [comment]
See my updated branch in the example repo: https://github.com/vmencik/akka-graal-native/tree/feature/wip-use-config-lib

Just `publishLocal` the lib repo with the same version.

**Comment by vmencik** [comment]
Also with Scala 2.13 the substitution for the scheduler is no longer necessary. Not sure why but `native-image` can recalculate the field automatically. Probably some change in the emitted bytecode.

But for Scala 2.13 we need another substitution to deal with `MethodHandle` used in `Statics.releaseFence()`.

**Comment by raboof** [comment]
It seems the graal `NativeImageBuildServer` gets confused when I `publishLocal` the library again under the same version number as before - indeed it picked up the `AkkaSubstitutions` fine :+1: .
