### ISSUE TITLE
Akka-remote support

### ISSUE THREAD

**Issue by gilles-degols** [vmencik/akka-graal-config#6]
Hello,
I was able to use your initial work [here](https://github.com/vmencik/akka-graal-native) to build a native-image of some Akka projects. The only big issue remaining is the use of akka-remote (tested with akka 2.5.22).

I can manage to compile the application, but impossible to launch it (internal timeout of 10s to instantiate the NettyTransport class, package akka.remote, Remoting.scala ~line 900). Modifying the related code to remove the reflection only leads to the following compilation error with GraalVM = "unstructured control flow  ( [, 560]  [, 672, 560, 517])" with stacktraces related to GraalVM & external Netty package.

Did you find a way to make GraalVM works with akka-remote? Or do you plan to do it inside this project? 
If it is necessary to provide a sample project I would be happy to do it (for now it is proprietary code but I can create a simpler project).

**Comment by raboof** [comment]
@gilles-degols I had quicker success with Artery TCP rather than Netty (or Aeron) remoting.

I ended up configuring Artery TCP and excluding the Netty and Aeron dependencies from the classpath entirely, and passing `--allow-incomplete-classpath` to `native-image`. That might work for you as well?

**Comment by gilles-degols** [comment]
@raboof Indeed, I tried with Artery (+ jackson serialization provided in akka 2.6) and it worked perfectly fine after adding the appropriate reflection configuration!
As you said, the `--allow-incomplete-classpath` was necessary to make it work.

Thank you very much for the tip!
